### ISSUE TITLE
Module Methods Look for 'index.html'

### ISSUE THREAD

**Issue by jpmedley** [SphinxKnight/compat-tester#10]
Here's the code:

```
const ct = require('compat-tester');
let report = ct.htmlFileAnalyzer('new-tab.html', 'scope.json');
console.log(report);
```

It's in a file called 'Index.js', run with:

`node index.js`

It gives this output:

```
Using index.html as the root and scope.json as the scope descriptor
undefined
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'index.html'
Emitted 'error' event at:
    at fs.js:2068:12
    at FSReqWrap.oncomplete (fs.js:153:20)
```

**Comment by SphinxKnight** [comment]
Thanks for reporting this! (it's a bit of a shame that I didn't test the module usage…)

This has been fixed with fcbca52271a456156371ba8681a7b2ddb6b929cd and published on NPM with the `0.2.5` version.

However, for now, the second argument of `htmlFileAnalyzer` is an object. In other words, updating the package, if you use:

    const ct = require('compat-tester');
    let scope = {"chrome":"57"} // or whatever scope you want :)
    let report = ct.htmlFileAnalyzer('new-tab.html', scope);
    console.log(report);

you should have something working :)

I'll close this issue and I've opened #11 in order to improve documentation about the arguments' type.
